baseURL = 'https://minigamefun.online/'
languageCode = 'en-US'
title = 'MiniGameFun'

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[build]
  useResourceCacheWhen = 'fallback'
