# SỬA DÒNG NÀY: Dùng tên miền mới của bạn, phải có https:// và dấu / ở cuối
baseURL = 'https://minigamefun.online/' 
languageCode = 'en-US'
title = 'MiniGameFun'

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[build]
  useResourceCacheWhen = 'fallback'